### ISSUE TITLE
MDC-103 iOS, Step 3: Syntax error

### ISSUE THREAD

**Issue by BigDada1** [material-components/material-components-ios-codelabs#36]
In **Apply the colors to the home screen**

**wrong**
`MDCAppBarColorThemer.applySemanticColorScheme(ApplicationScheme.shared.colorScheme,
to:self.appBar)`

**fixed**
`MDCAppBarColorThemer.applyColorScheme(ApplicationScheme.shared.colorScheme,
to: self.appBarViewController)`

**Comment by BigDada1** [comment]
Ah, this issue belongs to #30. The Swift/Obj-C code has been updated, [but not the tutorial](https://codelabs.developers.google.com/codelabs/mdc-103-swift/index.html?index=..%2F..index#2).

**Comment by romoore** [comment]
The tutorial has been republished. This issue should be fixed now.  Thanks for finding it!
